# 激活哪个环境下的配置
spring:
  profiles:
    active: dev
#################redis基础配置#################
    
server:
  port: 80

logging.level.com.gh.xiangsu.dao: debug


#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.0.194:3306/cjhj
#    username: root
#    password: root


##配置myBatis的映射文件
mybatis:
##给实体类起别名
  type-aliases-package: com.gh.xiangsu.entity
##引入mapper映射文件
  mapper-locations: classpath:mappers/*.xml
  configuration :
    call-setters-on-nulls: true
coin: 
  name: HTT
#每天短信验证码次数
sms: 
  verCode: 
    maxCount: 10