
##数据源的配置
spring:
  datasource:
    url: jdbc:mysql://rm-j6c3rf1g2vwupbb7l.mysql.rds.aliyuncs.com:3306/gh_xiangsu
    username: xiangsu
    password: xiangsu_2018
    poolMaximumActiveConnections : 20
    poolMaximumIdleConnections : 5
    poolPingQuery : select 1
    poolPingEnabled : true
    poolPingConnectionsNotUsedFor : 3600000
    #################redis基础配置#################
  redis:
    host:  r-j6c71db4873b5874.redis.rds.aliyuncs.com
    port: 6379
    password: xiangsu_2018
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
#################redis线程池设置#################
# 连接池中的最大空闲连接，默认值也是8。
    jedis:
      pool:
        max-idle: 500
  #连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
  # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 2000
  # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 1000
spgServer: 
  host: TIuoQGcAsMOSimVxwI+AOA==
  prot: 8+hNgn6Z/Mi1WS0iqZfRlg==
  userName: NGOjKIbq6mJp/ils+BCcDQ==
  password: DSjIHRr792a5ly83XsxOJQ==
bstServer: 
  host: mHBFjdFQSFhL+DgUVO0ZKQ==
  prot: 8+hNgn6Z/Mi1WS0iqZfRlg==
  userName: rqTgPjoXyW55fMyOYGOLBw==
  password: MDlcHlOuJ+TZTZFmC5tpCg==
btcServer: 
  host: 0RSeCyyVZtpj/MQSTtsfXQ==
  prot: e0PHWtTWEAze0kVpUQJbWA==
  userName: NEBCj+TcoakAC9FZKmwLPg==
  password: yyPmhcdWXy6E1k55++az8XIy3MjalYoXQzICg1FoeUI=
ltcServer: 
  host: 0RSeCyyVZtpj/MQSTtsfXQ==
  prot: ZXou3vOWEljN+Qj9PMGyuQ==
  userName: 04oBNiWXYQZrachc4e0a8w==
  password: /Ot67RGauhK7cmx/DsiPSHIy3MjalYoXQzICg1FoeUI=
img: 
  upload: 
    url: xiangsu/htt/
isdebug: 
  type: 0